### PR TITLE
Update settingsfile.php

### PR DESCRIPTION
**Pull request by LifeMushroom**

### CODE REVIEW

**Comment by MrRean** [comment]
Editing a small grammar error shouldn't be something to file a pull request on...try to bring CODE changes. (If it's a grammar error, just ask a person who can directly edit it.)

**Comment by LifeMushroom** [comment]
Meh. I am trying something code-related right now, but just thought this should happen.

**Comment by Tierage** [comment]
ABXD is long dead anyways. I think you should stop trying to contribute useless things...

**Comment by LifeMushroom** [comment]
Okay...fine...

**Pull request merged**
